### ISSUE TITLE
New default options not working for Rails version under 4

### ISSUE THREAD

**Issue by neolyte** [mailjet/mailjet-gem#104]
Under Rails version 4, the new default options in mailjet-gem/lib/mailjet/configuration.rb are NOT properly set.

To fix, one would have to add these manually in their configuration initializer.

```
Mailjet.configure do |config|
  config.api_key          = ENV['MAILJET_KEY']
  config.secret_key       = ENV['MAILJET_SECRET']
  config.default_from     = 'xxxx'
  config.perform_api_call = true
  config.api_version      = 'v3'
  config.end_point        = 'https://api.mailjet.com'
end
```

**Comment by Zhivko-Mailjet** [comment]
@neolyte 
Thanks for sharing this! We will investigate and get back to you as soon as we can.

**Comment by Zhivko-Mailjet** [comment]
Hi @neolyte 
We were researching the problem and should be able to apply a solution by the end of the week. We will keep you posted.

**Comment by arnaudbreton** [comment]
Hey @neolyte, as planned, #105 should fix the issue. Now merged back in master, can you please confirm it's working for you? 

We'll release 1.5.3 in the coming days.
Thanks for reporting and for having chosen Mailjet to power your emails.

**Comment by arnaudbreton** [comment]
Awesome, thanks @neolyte for confirming. Keep you posted on the release

**Comment by arnaudbreton** [comment]
v1.5.3 is live! https://github.com/mailjet/mailjet-gem/releases/tag/v1.5.3
