### ISSUE TITLE
Send email instructions (devise) from mailjet_api didn't work

### ISSUE THREAD

**Issue by karimgarcia** [mailjet/mailjet-gem#106]
Hi,
When I try to send mails with devise via mailjet_api, the body of messages is blank (no content). But if I configure with config.action_mailer.delivery_method = :mailjet that work fine.
have you got a solution to resolve this problem ?

**Comment by Lorel** [comment]
Hi @karimgarcia,

Thanks for reporting, we gonna try to fix that as soon as possible
Could you tell me if you use the default API version (v3) or the most recent one (v3.1)?

**Comment by karimgarcia** [comment]
We use the version 3.1
Thanks

**Comment by Lorel** [comment]
I think I found out what happened: only multipart (html + text) emails where handle by Mailjet::APIMailer, and Devise produces only singlepart HTML emails

As Mailjet::Mailer inherits from Mail::SMTP, there was not any issue by using it

A fix is in review, but you can give it a try by setting `gem 'mailjet', github: 'mailjet/mailjet-gem', branch: 'fix-issue-106'` in your Gemfile

Hope it will help

**Comment by karimgarcia** [comment]
It works!!
Thanks for the quick reply! @Lorel

**Comment by Lorel** [comment]
Great!
Iit will be a part of the next release, 1.5.3
We keep you updated

**Comment by arnaudbreton** [comment]
v1.5.3 is live, containing the fixes https://github.com/mailjet/mailjet-gem/releases/tag/v1.5.3

**Comment by karimgarcia** [comment]
thanks @arnaudbreton
