### ISSUE TITLE
problem with reply-to

### ISSUE THREAD

**Issue by karimgarcia** [mailjet/mailjet-gem#110]
Hi,
I used mailjet_api and tried to add a reply-to like this :
variable = Mailjet::Send.create( 
headers: {'Reply-To' => 'xxx@mesmidis.com'},
....
)
I receive the mail correctly but when I click on reply, I only can reply to my default address and not xxx@mesmidis.com

I have the version 3.1

Thank you
Karim

**Comment by Zhivko-Mailjet** [comment]
Hi @karimgarcia 

If you are using SendAPI v3.1 , the ReplyTo is not nested in the Headers collection, but has it's dedicated property instead. Also, there is no more dash in the middle.  You can check our transition hints for details:
https://dev.mailjet.com/beta/?ruby#send-api-v3-to-v3-1

**Comment by karimgarcia** [comment]
that doesn't work too : 
ReplyTo: {
                    "Name" => "xxxx",
                    "Email" => "xxxx@xxx.com"
                    },
...
Thank you for your answer

**Comment by Zhivko-Mailjet** [comment]
Hi @karimgarcia 

We just tested the the `ReplyTo` header with SendAPIv3.1 and it works fine  on our ednd. We believe it is not a problem with the wrapper. Please open a [support ticket](https://www.mailjet.com/support/ticket), providing full API call sample and we will be happy to continue investigating there.

**Comment by karimgarcia** [comment]
oh ok,
I will send a ticket to the support.
thanks for yours quick responses
I close this issue
