### ISSUE TITLE
Provide timeout configuration options for RestClient?

### ISSUE THREAD

**Issue by Tongboy** [mailjet/mailjet-gem#111]
Hi,

Love the gem!

Ran in to a scenario earlier this week when the API was down that caused some problems though.

Could the RestClient timeout values be exposed as configuration options? Ideally both the read & open as seperate options. The default of 60 seconds caused us some strife when the API was unreachable - we'd like to turn the open timeout down substantially but of course would prefer to not monkeypatch to do that.

https://github.com/rest-client/rest-client#timeouts has the details.

thank you!

**Comment by Zhivko-Mailjet** [comment]
@Tongboy Sorry about the delayed response.

Thank you for your suggestion. We will definetely look into this matter and get back to you when we have news. Of course, we will also be more than happy to review a contribution from your end.

**Comment by latanasov** [comment]
Hi @Tongboy the functionality was added with PR #117, we will soon release. Let me know if you experience any issues.

**Comment by Tongboy** [comment]
Thank you very much!

We'll implement it and let you know if we run in to any troubles.
