### ISSUE TITLE
Update contact not working ?

### ISSUE THREAD

**Issue by anthony-robin** [mailjet/mailjet-gem#122]
Hi, I try to update a Mailjet contact from my ruby code and can’t make it working. I tried:
```ruby
contact = Mailjet::Contact.find(<contact_id>)
contact.email = "newemail@example.com"
contact.save
```

and

```ruby
contact = Mailjet::Contact.find(<contact_id>)
contact.update_attributes(email: "newemail@example.com")
```

I returns me `true` but when I find the contact again, I still see the old email.

However, with the curl request explained in the [documentation](https://dev.mailjet.com/email-api/v3/contact/), it works properly.
Is there an issue with the gem ? What is the correct way to get the same curl request with the gem ?

Thanks for your help !

Details:
- Rails 3.2.22
- Mailjet 1.5.4

Edit: After debugging, it appears that payload is empty:
```
RestClient.put "https://api.mailjet.com/v3/REST/contact/<id>", "{}", "Accept"=>"application/json", "Accept-Encoding"=>"deflate", 
"Content-Length"=>"2", "Content-Type"=>"application/json", "User-Agent"=>"mailjet-api-v3-ruby/1.5.4"
# => 304 NotModified |  0 bytes
```

**Comment by latanasov** [comment]
Hi @anthony-robin thank you for finding this issue ! I will soon review your PR.
