### ISSUE TITLE
:segmentation_id not working on Newsletter update

### ISSUE THREAD

**Issue by neolyte** [mailjet/mailjet-gem#124]
When updating a newsletter campaign, the attribute :segmentation_id does not get passed (the segment stays the same)

For example:

campaign = Mailjet::Newsletter.find(id)
campaign.update_attributes(segmentation_id: new_id)

does not work.

The hack is to pass "SegmentationID" as such
campaign.update_attributes("SegmentationID": new_id)

Can we please add :segmentation_id to the resourceprop here https://github.com/mailjet/mailjet-gem/blob/master/lib/mailjet/resources/newsletter.rb ?

Thanks

**Comment by xab3r** [comment]
Fixed in v1.6.0
