### ISSUE TITLE
Retry operation if a Mailjet::ApiError happens

### ISSUE THREAD

**Issue by misterwolf** [mailjet/mailjet-gem#126]
While I was trying to retrieve a Mailjet List, the Mailjet API were down and the "Error 500" exception has been handled by the gem. 
In these case I need to repeat the operation but unfortunately the method Mailjet::Connection#handle_exception blocks the execution.
Is it possibile add the "retry" facility for these cases? 

Let me know,

Thanks

**Comment by mgrishko** [comment]
Sorry, but this is not the optimal way to put the retry business logic in the library. The application is responsible for this retry logic. Gem should only provide a connection for a third-party service or API.
