### ISSUE TITLE
ccs and bccs array not initialized lib/mailjet/mailer.rb

### ISSUE THREAD

**Issue by subzekt** [mailjet/mailjet-gem#130]
There seem to be wrong piece of code with the arrays being uninitialized prior to use.

NoMethodError: undefined method `<<' for nil:NilClass
from .../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mailjet-1.5.4/lib/mailjet/mailer.rb:167:in `block in setContentV3_1'

**Comment by Lorel** [comment]
indeed @subzekt, it is
it should be fixed by #132
thx
