### ISSUE TITLE
v3.1 docs

### ISSUE THREAD

**Issue by Frexuz** [mailjet/mailjet-gem#131]
There's nothing in the docs explaining this, and only stating `v3`. I had to look through the source.

Looking at `mailer.rb#L70`,  Is this config correct? **It still seems to send an email :/**
```
Mailjet.configure do |config|
  config.api_key = '...'
  config.secret_key = '...'
  config.default_from = '...'
  config.api_version = 'v3.1'
  config.sandbox_mode: !Rails.env.production?
end
```

https://github.com/mailjet/mailjet-gem/blob/0150ecd01be7a8e22bb71ff957b1ab566a747cd9/lib/mailjet/mailer.rb#L70

**Comment by latanasov** [comment]
Hi @Frexuz you can check the [guide](https://dev.mailjet.com/guides/?ruby#send-api-v3-1) on dev.mailjet.com. There is an open PR on this repo which should be merged.
