### ISSUE TITLE
Mailjet API 3.1

### ISSUE THREAD

**Issue by tbsvttr** [mailjet/mailjet-gem#139]
Is this Gem really only Mailjet API 3 or is it also 3.1?

**Comment by Lorel** [comment]
Hello @tbsvttr,

This gem works by default with the API v3, but it can work also on the API v3.1
You have to override the [default parameter](https://github.com/mailjet/mailjet-gem/blob/master/lib/mailjet/configuration.rb#L8) in your configuration
But I confess, this is not well documented
Tell us if you have any trouble for that

**Comment by tbsvttr** [comment]
@Lorel Thanks for the quick reply.

**Comment by tbsvttr** [comment]
Until now anything worked just fine.
