### ISSUE TITLE
"Mailjet API v3.1 is at the moment limited to Send API."

### ISSUE THREAD

**Issue by tbsvttr** [mailjet/mailjet-gem#143]
When will the rest of the functionality also be available on v3.1?

**Comment by Gogtsu** [comment]
After many headaches trying to make templates work with passport from the API I came to the same conclusion.

**Comment by netwire88** [comment]
Will 3.1 ever get Contact and other endpoints? What's the benefit of v3.1 vs. v3.0 for Send?

**Comment by ngarnier** [comment]
We have two different versions for Send API because v3.0 and v3.1 have different features, limits and contracts.

There is no point to have the rest of the endpoints as 3.1 as they would just be a duplication of all the v3.0 endpoints.
