### ISSUE TITLE
Spaces inside campaign name result in inappropriate URI to be requested

### ISSUE THREAD

**Issue by adaRn** [mailjet/mailjet-gem#145]
Consider a campaign name with spaces inside of it and an operation to fetch statistics from it.
```ruby
Mailjet::Campaignstatistics.find('3 Test Mario').opened_count
URI::InvalidURIError: bad URI(is not URI?): https://api.mailjet.com/v3/REST/campaignstatistics/3 Test Mario
	from /Users/sbrg/.rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/uri/common.rb:176:in `split'
	from /Users/sbrg/.rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/uri/common.rb:211:in `parse'
	from /Users/sbrg/.rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
```

The above raises an `URI::InvalidURIError`. That's because the unescaped spaces are there in the URL from the campaign name.

If we, however, URI-escape the campaign name, everything works fine.
```ruby
Mailjet::Campaignstatistics.find(URI.escape('3 Test Mario')).opened_count
=> 1
```

If I may suggest a solution, then it'd be doing `URI.escape` on resource `id` in the definition of `create_action_resource_path` in `lib/mailjet/resource.rb`.

**Comment by xab3r** [comment]
Fixed in v1.6.0
