### ISSUE TITLE
Mailjet memory consumption 

### ISSUE THREAD

**Issue by miguelpeniche** [mailjet/mailjet-gem#147]
More than an issue, is a suggestion. I am doing memory benchmarks in a rails application with 215 gems installed (rails and dependencies). And Mailjet gem is the second most memory consumer, just after rails. Maybe is time to remove some dependencies or refactor code?

![captura de pantalla 2018-06-06 14 07 40](https://user-images.githubusercontent.com/3253845/41059819-48cd4130-6993-11e8-9430-bf347607af06.png)

![captura de pantalla 2018-06-06 14 06 09](https://user-images.githubusercontent.com/3253845/41059735-0509867a-6993-11e8-9f00-d35d886a2a6d.png)

**Comment by mgrishko** [comment]
Released new version with refactoring
