### ISSUE TITLE
Validate Sender

### ISSUE THREAD

**Issue by c2ofh** [mailjet/mailjet-gem#157]
Hi, I want to create a new sender.
So I've used 
```ruby
Mailjet::Sender.create(email: 'name@domain.de')
```
The answer was, that a deleted user already exists. So I found the deleted sender via
```ruby
Mailjet::Sender.find(email: 'name@domain.de')
=>  {"persisted"=>true,
     "created_at"=>Sat, 20 Oct 2018 01:20:27 +0000,
     "dnsid"=>1234567,
     "email"=>"name@domain.de",
     "email_type"=>"unknown",
     "filename"=>"",
     "id"=>123456789,
     "is_default_sender"=>false,
     "name"=>"",
     "status"=>"Deleted"}
```

The DNS is nil if I want to request the spf and dkim information.
How to validate this email as a sender?

Via POST Request to https://api.mailjet.com/v3/REST/sender/name@domain.de/validate I recieve this information:
```ruby
{
    "ValidationMethod": "ActivationEmail",
    "Errors": {
        "FileValidationError": "",
        "DNSValidationError": ""
    },
    "GlobalError": ""
}
```

**Comment by etouraille** [comment]
How dit you solved that, I Have got the same issue ?

**Comment by c2ofh** [comment]
@etouraille Sorry, we switched to another provider, so there was no solution needed anymore.
