### ISSUE TITLE
Mailjet & Devise

### ISSUE THREAD

**Issue by monroemann** [mailjet/mailjet-gem#159]
Hello,

We are a paying customer of MailJet.  I have followed all instructions on this repos read-me, but I'm having trouble connecting the API up to the Devise 'reset password' form.  

1. Are there instructions anywhere for helping to link up MailJet to Devise? I must be missing a step somwhere.  When I click 'Send Password Reset Link', I receive an error: email is required.  But my email address IS there.

2. If there are no pre-written guides on how to do this, could someone kindly help with the particular steps I need to take to ensure that when I press 'Send Password Reset Link' on our devise sign-in page, it properly sends the email?

3. Next, is this testable on localhost, or is the only way to test to go live on heroku?

4. Finally, do I have to do anything on Heroku itself to link up to my MailJet account?

Thanks!
-Monroe

**Comment by xab3r** [comment]
Sorry for the late reaction to your question. Closing since this is not an issue anymore.
