### ISSUE TITLE
Messagehistory only returns first event

### ISSUE THREAD

**Issue by ArthurWD** [mailjet/mailjet-gem#160]
When calling this:
```Mailjet::Messagehistory.find(message_id, nil, version: 'v3')```

I only get the first event. This is caused by #first on line 83 of Resource:
```attributes = parse_api_json(connection(opts)[id].get(default_headers)).first```

Not sure what the cleanest way is to fix this. When using `Mailjet::Messagehistory.find`, the message_id is not set in the url.

**Comment by xab3r** [comment]
Fixed in v1.6.0
