### ISSUE TITLE
Could you guys do a new release that includes sandbox mode

### ISSUE THREAD

**Issue by johannesluedke** [mailjet/mailjet-gem#161]
Since 1.5.4 in mid 2017 there was no new version released. It would be nice to have a version that contains f.e. the sandbox mode #120 that got added in October 2017.

Can you please make a new release?

**Comment by tirrorex** [comment]
@johannesluedke i send an email to the dev team, might get lucky and have a reply. Will keep you updated.

**Comment by caseyprovost** [comment]
Following up on this. The gem's latest release is also incompatible with rails 5 and 6. Are these things on the roadmap?
