### ISSUE TITLE
No error if from is empty but then message not found

### ISSUE THREAD

**Issue by armandmgt** [mailjet/mailjet-gem#166]
When sending a template email without `from` (meaning it is defined by the template), the API responds with `200 OK`, `status: "success"` and `MessageID`
But then `GET /v3.1/REST/message/{MessageID}` returns `404 NOT FOUND`

**Comment by xab3r** [comment]
Try `GET /v3/REST/message/{MessageID}`. Looks like it's not available in 3.1
