### ISSUE TITLE
Listrecipient.all(limit:0) misleading

### ISSUE THREAD

**Issue by Uepsilon** [mailjet/mailjet-gem#167]
According to the [documentation](https://github.com/mailjet/mailjet-gem#get-all-the-recipients-in-one-query) the param `limit: 0` should return ALL recipients but returns only 1000. 

also, when using `limit: 0`, `offset` is not working.

```ruby
irb(main):033:0> Mailjet::Listrecipient.all(list_id: XYZ, limit: 0).count
=> 1000
irb(main):034:0> Mailjet::Listrecipient.all(list_id: XYZ, limit: 0, offset: 1000).count
=> 1000

irb(main):035:0> Mailjet::Listrecipient.all(list_id: XYZ, limit: 1000).count
=> 1000
irb(main):036:0> Mailjet::Listrecipient.all(list_id: XYZ, limit: 1000, offset: 1000).count
=> 174
```

**Comment by xab3r** [comment]
The documentation is updated. `.all` returns up to 1000 entries regardless of `limit` option. https://github.com/mailjet/mailjet-gem#retrieve-all-objects
