### ISSUE TITLE
in v3.1 incorrect Mailjet::APiError code

### ISSUE THREAD

**Issue by blset** [mailjet/mailjet-gem#177]
Hello

in v3.1, when sending a message with several recipients, if one of the email is blocked by mailjet, the whole response of the message is an  api error.

the result is that when using for instance sidekiq as a job processior, it keeps sending the same message ever and ever because the response is interpreted as an error.

you end up with a huge bill from mailjet, because from their part they have processed the messages.

so would it be possible to modify that behaviour so that when sending multiple mails with not all individual success, the whole batch is not seen as an error.

thanks

**Comment by xab3r** [comment]
Is this still an issue?
Can you please provide more details on how exactly you send messages?

**Comment by Retttro** [comment]
Fixed in version 1.7.1. Closing.
