### ISSUE TITLE
Ruby API pass in array

### ISSUE THREAD

**Issue by netwire88** [mailjet/mailjet-gem#184]
I'm having trouble passing an array using the Ruby API. I've followed https://www.mailjet.com/blog/news/template-error-management-mailjet/  and https://dev.mailjet.com/email/template-language/reference/ and I'm getting error: 
`expression parsing error ## Unknown identifier: value ## near ## {{value ##`

The Passport block is
```
   <ul>
      {% for value in var:x %}
      <li>{{value}}</li>
      {% endfor %}
</ul>
```

My Ruby code is
```
   result = Mailjet::Send.create(
        messages: [{
                       'From'=> {
                           'Email'=> "alerts@test123.com",
                           'Name'=> "TEST Alerts"
                       },
                       'To'=> [
                           {
                               'Email'=> 'test1@test123.com',
                               'Name'=> 'TEST'
                           }
                       ],
                       'TemplateID'=> 1163244,
                       'TemplateLanguage'=> true,
                       'Subject'=> "Test 3231",
                       'Variables'=> {
                           'name' => 'Test User',
                           'x' => [1, true, 'Pilot']
                       }
                   }])
```
I've tried changing single quotes to double quotes. I've tried using ":" instead of "=>" but nothing works. Any suggestions?

**Comment by xab3r** [comment]
Could you please provide an error stack trace? Can you send it using `curl`?

**Comment by StrausT-UMG** [comment]
Hi @netwire88 - did you ever get to the bottom of this issue? I am facing a similar issue with Mailjet right now.

**Comment by netwire88** [comment]
No @StrausT-UMG , we switched to another SaaS company instead

**Comment by StrausT-UMG** [comment]
Got it @netwire88 - thank you!
