### ISSUE TITLE
StatusCode 410 not in the docs

### ISSUE THREAD

**Issue by marcel12bell** [mailjet/mailjet-gem#186]
I'm using Mailjet::Messagesentstatistics since years, now I get 
Mailjet::ApiError (error 410 while sending #<RestClient::Resource:0x00007f22e26f0e08 @url="https://api.mailjet.com/v3/REST/messagesentstatistics"
point has been deprecated for new users as from March, 15 2018. Please use \\/statcounters endpoint instead\", \"StatusCode\" : 410 }"

I can not find the code in the docs:
https://dev.mailjet.com/email/reference/overview/errors/

Is there an alternative to Mailjet::Messagesentstatistics ? See https://dev.mailjet.com/email/reference/statistics/#v3_get_statcounters

**Comment by mgrishko** [comment]
We would like to inform you that [this endpoint ](https://dev.mailjet.com/email/reference/statistics#v3_get_messagestatistics_message_ID)has been deprecated, and we intend to update this library in our next release. Thank you for your understanding.
