### ISSUE TITLE
unauthorized action cancancan

### ISSUE THREAD

**Issue by boivinremi** [mailjet/mailjet-gem#187]
I'm trying to configure cancancan in my app. All it's work except the mailler he says 

> 783: unexpected token at 'Not authorized

I try to skip authorisation checks on the mailer but isn't work.
https://gist.github.com/boivinremi/c3ab8d889326570c8e2d6ede92d32efb
I don't if it a bug in mailjet, in cancancan or if it's me
Thanks

**Comment by xab3r** [comment]
Have you [configured](https://github.com/mailjet/mailjet-gem#authentication) mailjet properly? Is this still an issue?

**Comment by xab3r** [comment]
closed due to inactivity
