### ISSUE TITLE
"in-v3.mailjet.com" does not match the server certificate

### ISSUE THREAD

**Issue by codyrickman** [mailjet/mailjet-gem#188]
Hello, I keep getting `OpenSSL::SSL::SSLError (hostname "in-v3.mailjet.com" does not match the server certificate):`

in my production environment only. I have a valid SSL cert for my domain. 

My mailjet.rb file:
`Mailjet.configure do |config|
  config.api_key = 'xxxxxxxxx'
  config.secret_key = 'xxxxxxx'
  config.default_from = 'info@domain.com'
  config.end_point = "https://api.us.mailjet.com"
  config.api_version = 'v3.1'
end`

production.rb
`config.action_mailer.delivery_method = :mailjet`

**Comment by codyrickman** [comment]
bump** any update on this?

**Comment by xab3r** [comment]
is this still an issue?

**Comment by mgrishko** [comment]
No answers. I close this issue
