### ISSUE TITLE
FATAL -- : [12421295-5b4a-4afa-828e-166f88779600] Net::OpenTimeout (execution expired):

### ISSUE THREAD

**Issue by certilremy** [mailjet/mailjet-gem#191]
I'm using This gem on a Previous project, it's live no bug sends email correctly. But now I'm working on a new project for a client with rails 6 I send email in development.  when I build an publish the project I can't send emails on production. When I inspect the log I found the following errors:

`I, [2020-07-30T22:31:45.446874 #16670]  INFO -- : [12421295-5b4a-4afa-828e-166f88779600] Completed 500 Internal Server Error in 30346ms (ActiveRecord: 5.7ms | Allo
cations: 8276)
F, [2020-07-30T22:31:45.447683 #16670] FATAL -- : [12421295-5b4a-4afa-828e-166f88779600]   
[12421295-5b4a-4afa-828e-166f88779600] Net::OpenTimeout (execution expired):
`

Note I'm using the same hosting provider and even tho I sed the same code I still got the errors and the app crash

**Comment by xab3r** [comment]
Is this still an issue?
Could you please provide more details? Would be good to have gem version, mailjet API endpoint you are calling, and parameters, maybe with code samples.

**Comment by xab3r** [comment]
closed due to inactivity
