### ISSUE TITLE
ActionMailer + Campaigns?

### ISSUE THREAD

**Issue by justalever** [mailjet/mailjet-gem#215]
I'm struggling to use the campaign features of the API. At the moment I can create and send single emails with ease but using ActionMailer I've hit a roadblock on how to go about sending to multiple recipients via the API.

Is this possible with ActionMailer or will I need to use the API to create Campaign drafts and then send them more manually?

The docs have this outlined [here](https://dev.mailjet.com/email/reference/campaigns/drafts#v3_post_campaigndraft). The problem I run into is getting the mailer HTML inside my rails app to append to the campaign content. Without ActionMailer it's quite a pain... 

My goal is to create a new campaign per mailing. Similar to a weekly newsletter. 

Any insight here on how to leverage the gem to hook into a campaign would be great!

**Comment by Retttro** [comment]
You can use ActionMailer with mailjet, here you can find more details https://github.com/mailjet/mailjet-gem#send-emails-with-actionmailer. Also, you can provide a `CustomCampaign` option which will specify a campaign that should be used when sending. More details about the `CustomCampaign` option can be found here https://dev.mailjet.com/email/reference/send-emails#v3_1_post_send.
