### ISSUE TITLE
I'm facing the same issue with just a basic hello world email template.

### ISSUE THREAD

**Issue by dharani-gaddam** [mailjet/mailjet-gem#240]
I'm facing the same issue with just a basic hello world email template.

```
Mailjet::Send.create(messages: [{
  'From'=> {
    'Email'=> "abc@gmail.com",
    'Name'=> "abc"
  },
  'To'=> [
    {
      'Email'=> 'xyz@gmail.com',
      'Name'=> 'xyz'
    }
  ],
  'TemplateID'=> 12345,
  'Subject'=> "Test email using mailjet api",
  'TemplateLanguage'=> true,
  'Variables'=> {
    "firstname" => "xyz"
  }
}])
```

getting this error:
**NoMethodError: undefined method `include?' for nil:NilClass**

Can you please check @WeshGuillaume 
Thanks in advance
Dharani

_Originally posted by @dharani-gaddam in https://github.com/mailjet/mailjet-gem/issues/62#issuecomment-1369955695_

**Comment by mgrishko** [comment]
Fixed in https://github.com/mailjet/mailjet-gem/pull/244
