### ISSUE TITLE
Mailjet domain

### ISSUE THREAD

**Issue by bradleypriest** [mailjet/mailjet-gem#38]
Your README talks about setting a config for domain, however it actually throws an error if you try to set it

**Comment by swooop** [comment]
Hi Bradley, which error does it throw?

I think this is related to another issue, let me investigate and get back to you ASAP.

All the best,

Toby.

**Comment by swooop** [comment]
With no more information, I'm afraid I can't narrow this down any further to see if it's the gem or an API configuration issue.
I'll keep looking.

**Comment by bradleypriest** [comment]
Simply try it out yourself, there's no attr_writer on the class. It is almost definitely just an out of date read me. 



—
Bradley Priest

**Comment by swooop** [comment]
Ah, apologies, I got the wrong end of the stick - I'll dig through previous commits and see what changed, or update the readme as appropriate.

**Comment by swooop** [comment]
Do you get the undefined method 'domain' error?

**Comment by bradleypriest** [comment]
Yep, I think so, this is going back a while

**Comment by swooop** [comment]
You were completely correct, it was an out of date readme. Thanks for the spot, I've amended.
