### ISSUE TITLE
Get the email ID of an email sent with ActionMailer

### ISSUE THREAD

**Issue by UgoMare** [mailjet/mailjet-gem#39]
Hi,
I can't get the ID of an email sent with the delivery_method :mailjet_api. 
In lib/mailjet/mailer.rb Mailjet::APIMailer .deliver!() you use the Mailjet::MessageDelivery.create() which return an object with an email ID but with ActionMailer I can't find a way to get it.
I would like to track some emails by their ids (with the middleware) instead of the email address because I track some specific emails.
Thanks,
Ugo

**Comment by swooop** [comment]
Ugo,

Apologies for the delay in responding - I'll have a look into this and get back to you.

All the best,

Toby

**Comment by swooop** [comment]
Hi Ugo,
Using:
```ruby
some_email = Mailjet::MessageDelivery.create(from: "myemail@email.com", to: "email@recipient.com", subject: "Mailjet mail ID's", text: "Lets have a look")
```

The variable *some_email* now contains something like the following:
```ruby
#<Mailjet::MessageDelivery:0x007ff8e31a87e8
 @attributes={"persisted"=>false, "from"=>"myemail@email.com", "to"=>"email@recipient.com", "subject"=>"Mailjet mail ID's", "text"=>"Lets have a look", "id"=>19421777694478490},
 @persisted=true>
```

To extract the id from this, we can access the @attributes variable like so:
```ruby
some_mail.attributes["id"]
#which should return:
=> 19421777694478490
```

Does this help?

All the best,

Toby.

**Comment by UgoMare** [comment]
Hi Toby,
thanks for your answer but I tried this technique and the point is I would like to use templates and attachments like ActionMailer provides. There is any way to do it ?

**Comment by swooop** [comment]
Hi Ugo,

Does this work for you : http://api.rubyonrails.org/classes/ActionMailer/Base.html#method-i-attachments ?

At the moment, we do not support templating.

**Comment by swooop** [comment]
Hi Ugo,

Going back to your point about Action Mailer Ids, when you create an email, you should get Mail::Message object something like this:
```#<Mail::Message:70130679620320, Multipart: false, Headers: <Date: Mon, 08 Jun 2015 12:38:34 +0100>, <From: you@example.com>, <To: me@example.com>, <Message-ID: <55757eba7d7a7_95063fc892052464416b1@somewhere>>, <Subject: Test mail>, <Mime-Version: 1.0>, <Content-Type: text/plain>, <Content-Transfer-Encoding: 7bit>>```

If you save this in a variable for convenience, you should be able to access the message ID with:
```
emailvarname.message_id
```

As for the attachments, let me know how it's going.

All the best,

Toby.

**Comment by itschn** [comment]
i think that not the actionmailer message id is meant, but the mailjet mail id. its essential for working with the webhooks/Event tracking feature. So how to get it from Mail::Message instance?

**Comment by GuillaumeBadi** [comment]
Hi !
When sending an email, you can provide a custom id `'mj-customid'` to be able to track the message and retrieve it via the Mailjet API

Best,
Guillaume

**Comment by itschn** [comment]
@GuillaumeBadi thanks

**Comment by GuillaumeBadi** [comment]
Please let me know if it works with you implementation ! If it solves the problem, you might just close the issue @UgoMare, otherwise I would be happy to help ! :)

**Comment by itschn** [comment]
it works

**Comment by pathros** [comment]
> Hi Ugo, Using:
> 
> ```ruby
> some_email = Mailjet::MessageDelivery.create(from: "myemail@email.com", to: "email@recipient.com", subject: "Mailjet mail ID's", text: "Lets have a look")
> ```
> 
> The variable _some_email_ now contains something like the following:
> 
> ```ruby
> #<Mailjet::MessageDelivery:0x007ff8e31a87e8
>  @attributes={"persisted"=>false, "from"=>"myemail@email.com", "to"=>"email@recipient.com", "subject"=>"Mailjet mail ID's", "text"=>"Lets have a look", "id"=>19421777694478490},
>  @persisted=true>
> ```
> 
> To extract the id from this, we can access the @attributes variable like so:
> 
> ```ruby
> some_mail.attributes["id"]
> #which should return:
> => 19421777694478490
> ```
> 
> Does this help?
> 
> All the best,
> 
> Toby.

How do you track the email delivery status with that given ID? What is the API url? I can't find it in the docs of MailJet
