### ISSUE TITLE
ruby syntax filters do not work properly

### ISSUE THREAD

**Issue by Electron-libre** [mailjet/mailjet-gem#41]
```ruby
 Mailjet::Contact.all('ContactsList' => remote_list.id)
=> []
```

This sound ok because this list is empty, but with underscored syntax:
```ruby
Mailjet::Contact.all(:contacts_list => remote_list.id)
=> [#<Mailjet::Contact:0x000000084b5818
  @attributes=
   {"persisted"=>true,
    "created_at"=>Tue, 26 May 2015 14:47:47 +0000,
    "delivered_count"=>0,
    "email"=>"abc@test.com",
    "id"=>1,
    "is_opt_in_pending"=>false,
    "is_spam_complaining"=>false,
    "last_activity_at"=>Tue, 26 May 2015 14:47:47 +0000,
    "last_update_at"=>"",
    "name"=>"",
    "unsubscribed_at"=>"",
    "unsubscribed_by"=>""}>,
 #<Mailjet::Contact:0x000000084b46c0
```

It should be empty !

The first workaround could be to update filters documentation.
If I have enougth time I'll have a closer look to provide a fix.

**Comment by swooop** [comment]
I'll have a look at the filters and check it's not API related, thanks for bringing this up

**Comment by Electron-libre** [comment]
I've done few tests with curl against the contact resource.
Using filters works with query string but not with json payload. Maybe this could explain the issue.
The API documentation is not really explicit around this.

**Comment by swooop** [comment]
Awesome - thanks for that, we'll look into it. 

Much appreciated.

**Comment by swooop** [comment]
Ah, ok, I see what's happening here - when you use:
```
Mailjet::Contact.all('ContactsList' => remote_list.id)
#or
Mailjet::Contact.all(:contactslist => remote_list.id)
```
The filters passed in are formatted into a query string by the gem. 
When the filters are correctly formatted:
```
https://api.mailjet.com/v3/REST/contact?contactslist=1
```
You get the required response.

When the filters are incorrect, the API ignores them, for instance if a raw API call is something like:
```
# A GET to:
https://api.mailjet.com/v3/REST/contact?contcatlis=1
```

It then defaults to what is effectively:
```
Mailjet::Contact.all
```

And you get the 'all' call for the resource.

I think implementing filter checking could be quite challenging as there are so many over so many resources, so it might be best to add a note to the readme.

You are correct, the API does not support filtering by JSON payload.

Hope that helps, all the best,

Toby

**Comment by Electron-libre** [comment]
What lead to confusion is this : https://github.com/mailjet/mailjet-gem#naming-conventions

When I use `:contact_list` as a filter I expect it to be sent as `ContactList` and the query should succeed.
The issue I think is that filters are not converted to camelcase.

**Comment by swooop** [comment]
You're quite right - I'll have a look through previous commits and see what changed.

**Comment by GuillaumeBadi** [comment]
Hi !

Sorry for the delay, and thanks for that relevant issue. You might take a look at the `filters` branch, which we are soon going to release into `master`. It automatically convert `:snake_case_symbols` into `'CamelCaseString'` so both of your examples would work ! 
You may need to consider a few days before the merge, but you can already use the feature.

Regards,
Guillaume

**Comment by GuillaumeBadi** [comment]
Hi @Electron-libre ! 

If you have any other suggestion, i would be happy to help ! Otherwise, please consider closing the issue :)

Regards,
Guillaume

**Comment by Electron-libre** [comment]
Hi, 
Sounds great. Thanks for your feedback and fixes. 

Kind Regards
