### ISSUE TITLE
exception handling failure when content_type is set to json

### ISSUE THREAD

**Issue by Electron-libre** [mailjet/mailjet-gem#42]
in `Mailjet::Connection#handle_api_call`
when exception occur and 
```ruby
additional_headers[:content_type]
=> :json
```
json parsed payload is passed to `Mailjet::Connection#handle_exception` which expect it as hash, not json string.

This result in
```
TypeError: can't convert String into Hash
from /lib/mailjet/connection.rb:74:in `merge'

```

**Comment by swooop** [comment]
Thanks very much and well spotted - we've got an impending update coming, and we'll merge this in then, with thanks!

**Comment by swooop** [comment]
Merged with thanks.
