### ISSUE TITLE
How to create Campaign?  Mailjet::MethodNotAllowed Mailjet::Campaign.create

### ISSUE THREAD

**Issue by zephiro** [mailjet/mailjet-gem#45]
Use 
        campaign = Mailjet::Campaign.create(title: "")

Error

Mailjet::MethodNotAllowed

**Comment by GuillaumeBadi** [comment]
Hi @zephiro ! Sorry for the delay !

You cannot create a raw Campaign this way. A campaign is automatically created when you create a newsletter. To get started with the API, I highly encourage you to read our documentation: http://dev.mailjet.com/

Regards,
Guillaume

**Comment by GuillaumeBadi** [comment]
Hi @zephiro !

Did it answered your question ? If yes, can you please close that issue ?
Otherwise, I would be happy to help ! 

Regards, 
Guillaume
