### ISSUE TITLE
Create user in list

### ISSUE THREAD

**Issue by judemoutiez** [mailjet/mailjet-gem#47]
How can I create a user within a specific list ?

Is it through the Listrecipient API ? Which parameters have to be passed ?

**Comment by GuillaumeBadi** [comment]
Hi @judemoutiez and thank you for using Mailjet !

A simple way to create a contact through the API is to use `contactslist/:id/managecontact`
Once you created a list, and you know its ID, you can create a contact within that list by using the `Mailjet::Contactslist_managecontact` class

``` ruby
Mailjet::Contactslist_managecontact.create(id: <your list id>, action: "addnoforce", email: "example@me.com", name: "Guillaume")
```

then you can check if it works via curl for example:
``` bash
curl -X GET --user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" https://api.mailjet.com/v3/REST/contact/?contactslist=<you list id> | python -m json.tool
```

I hope it helped !

Regards, 
Guillaume from Mailjet

**Comment by GuillaumeBadi** [comment]
Hi @judemoutiez !

Please let me know if you didn't manage to make it work on your side, I'd take some more time to help you on the implementation. Otherwise, could you please close the issue ?

Regards,
Guillaume;

**Comment by judemoutiez** [comment]
Hi Guillaume !

Thanks for your answer

I used the solution you gave me and it appears to be working, but not every single time.

When I test the line in the console, I manage to create a user, and if I try to create another one right after with another mail & name, I get this error:

"{ \"ErrorMessage\" : \"Object properties invalid\", \"StatusCode\" : 400, \"ErrorInfo\" : { \"Email\" : \"MJ08 Property email is invalid: MJ03 A non-empty value is required\", \"Action\" : \"Invalid action: \" } }"

The same seems to be happening on the website

Do you have an idea on what is happening ?

Thanks !

**Comment by GuillaumeBadi** [comment]
Hi !

I can't reproduce your error ! Can you paste a code snippet so I can try it on my side ? Here's what I've done so far:
![screen shot 2015-09-07 at 15 08 18](https://cloud.githubusercontent.com/assets/6558790/9717384/9bedca8e-5572-11e5-8721-1c5a3f163c97.png)

**Comment by judemoutiez** [comment]
Hi !

Here is what I get in the console

```
Loading development environment (Rails 4.1.4)
irb(main):001:0> Mailjet::Contactslist_managecontact.create(id: 16, action: "addnoforce", email: "test@me.com", name: "Julien")
=> #<Mailjet::Contactslist_managecontact:0x00000007e02520 @attributes={"persisted"=>false, "id"=>16, "action"=>"addnoforce", "email"=>"test@me.com", "name"=>"Julien", "contact_id"=>1489758118}, @persisted=true>
irb(main):002:0> Mailjet::Contactslist_managecontact.create(id: 16, action: "addnoforce", email: "secondtest@me.com", name: "Julienbis")
Mailjet::ApiError: error 400 while sending #<RestClient::Resource:0x00000007e51800 @url="https://api.mailjet.com/v3/REST/contactslist/16/managecontact", @block=nil, @options={:public_operations=>[:post], :read_only=>nil, :user=>"946d4e4bd4ddaed42b4dc487d0ab6593", :password=>"c16aae64be13fb5b7f8791b2954be65a", :content_type=>"application/json"}> to https://api.mailjet.com/v3/REST/contactslist/16/managecontact with {}

"{ \"ErrorMessage\" : \"Object properties invalid\", \"StatusCode\" : 400, \"ErrorInfo\" : { \"Email\" : \"MJ08 Property email is invalid: MJ03 A non-empty value is required\", \"Action\" : \"Invalid action: \" } }"

Please see http://api.mailjet.com/0.1/HelpStatus for more informations on error numbers.
```

**Comment by GuillaumeBadi** [comment]
Hey Julien !

It is indeed really confusing. I don't know if it comes from you account or the rails/mailjet compatibility.. I still can't get the same error on my side. What output do you get if you issue this line in the terminal:

(do it twice with a different email and a different name)

``` bash
curl -s -X POST --user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" https://api.mailjet.com/v3/REST/contactslist/16/managecontact -H "Content-Type: application/json" -d '{"Action": "addnoforce", "Email": "test-github@contact.com", "Name": "test github"}'
```

Thanks .
Guillaume ! :)

PS: remember not to publicy post your credentials (apikey/apisecret) ;)

**Comment by GuillaumeBadi** [comment]
Hey @judemoutiez !

I finally managed to reproduce your error. Thank you so much for the issue ! You might want to take a look at the rails_fix: branch. It looks like it fixes it. I just need to implement some more testing, but it should do the job ! 

Best,
Guillaume

**Comment by judemoutiez** [comment]
Hello Guillaume !

Thank you very much, I'll have a loot at it :)

**Comment by GuillaumeBadi** [comment]
Hi @judemoutiez !

Please keep me up to date ! :)

Best, 
Guillaume.

**Comment by judemoutiez** [comment]
Works perfectly, thanks a lot !
