### ISSUE TITLE
Contactslist_managecontact sending an error

### ISSUE THREAD

**Issue by judemoutiez** [mailjet/mailjet-gem#54]
Hello,

We've received a lot of emails from users in the past two days telling us that they can't verify their account and subscribe to our newsletter.

This is what I get in development : 

error 401 while sending #<RestClient::Resource:0x007fb17730b030 @url="https://api.mailjet.com/v3/REST/contactslist/1450104/managecontact", @block=nil, @options={:public_operations=>[:post], :read_only=>nil, :user=>nil, :password=>nil, :content_type=>"application/json"}> to https://api.mailjet.com/v3/REST/contactslist/1450104/managecontact with {"Email"=>"julien.demoutiez@gmail.com", "Action"=>"addforce"} "" Please see http://api.mailjet.com/0.1/HelpStatus for more informations on error numbers.

Here is my code:
Mailjet::Contactslist_managecontact.create(id: 1450104, action: "addforce", email: @email)

Can you please try to fix it as soon as possible ?

Thanks,

Julien

**Comment by GuillaumeBadi** [comment]
Hey ! @judemoutiez !

401 means 'unauthorized', can you print out your credentials and ensure they are correct before making the the call ?

Best,
Guillaume

**Comment by judemoutiez** [comment]
OK my mistake sorry guys !

Thanks for your swift answer :)

**Comment by GuillaumeBadi** [comment]
It happens to the bests of us ;)
