### ISSUE TITLE
GET user info by email

### ISSUE THREAD

**Issue by judemoutiez** [mailjet/mailjet-gem#55]
I have several contact lists and would like to request a user by email address within one of these lists. How would I do that ?

For now I do Mailjet::Contact.find(@user.email), but I'm not sure the user requested is in the right contact list.

Thank you !

**Comment by GuillaumeBadi** [comment]
Hey @judemoutiez !

Does that work for you ?
``` ruby 
variable = Mailjet::Listrecipient.all('ContactALT': '@contactID', 'ListID': @listID)
```

**Comment by judemoutiez** [comment]
Thanks @GuillaumeBadi 

Unfortunately I get 10 contacts and not the one I am requesting

**Comment by GuillaumeBadi** [comment]
My bad..

``` ruby
variable = Mailjet::Listrecipient.all(contact_email: 'email adress', contacts_list: list_id)
```

**Comment by judemoutiez** [comment]
Works great, thanks !
