### ISSUE TITLE
ReplyTo in ActionMailer missing?

### ISSUE THREAD

**Issue by chbach** [mailjet/mailjet-gem#56]
Hi, 

I wanted to use Mailjet with Rails' ActionMailer and tried to use the `reply_to:` option. I quickly checked your implementation and found nothing about it. Is it really not implemented or did I miss something here? https://github.com/mailjet/mailjet-gem/blob/master/lib/mailjet/mailer.rb#L40

Regards, 
Christoph

**Comment by GuillaumeBadi** [comment]
Hey @chbach !
Sorry for the delay, I added it in the previous release
