### ISSUE TITLE
Inconsistency on contact data depending on the method being called.

### ISSUE THREAD

**Issue by bbnnt** [mailjet/mailjet-gem#59]
Very hard to find  a real coherence in your api.

`Mailjet::Contact.find("adresseemail@tld.com")`

tells me the id is an email :
```
#<Mailjet::Contact:0x007f969f151b38 @attributes={
"persisted"=>true,
"created_at"=>Thu, 28 Jan 2016 09:07:10 +0000,
 "delivered_count"=>1,
"email"=>"adresseemail@tld.com",
"exclusion_from_campaigns_updated_at"=>"",
"id"=>"adresseemail@tld.com",
"is_excluded_from_campaigns"=>false,
"is_opt_in_pending"=>false,
"is_spam_complaining"=>false,
"last_activity_at"=>Tue, 01 Mar 2016 14:29:08 +0000
 "last_update_at"=>"",
"name"=>"",
"unsubscribed_at"=>""
 "unsubscribed_by"=>""}> 
```
Just to double check :
```
Mailjet::Contact.all.each do |c|
puts c.inspect
end; nil
```

tells me the id is numeric :

```
...
#<Mailjet::Contact:0x007f969cdb92e8 @attributes={
"persisted"=>true,
"created_at"=>Thu, 28 Jan 2016 09:07:10 +0000,
"delivered_count"=>1,
"email"=>"adresseemail@tld.com",
"exclusion_from_campaigns_updated_at"=>"",
"id"=>14541765,
"is_excluded_from_campaigns"=>false,
"is_opt_in_pending"=>false,
"is_spam_complaining"=>false,
"last_activity_at"=>Tue, 01 Mar 2016 14:29:08 +0000,
"last_update_at"=>"",
"name"=>"",
"unsubscribed_at"=>"",
"unsubscribed_by"=>""}>
...
```

as developpers, what should your we think about the mailjet api ?

I was just trying to update some users data :
```Mailjet::Contactdata.create(:contact_id => "adresseemail@tld.com", :data => [ {"Name" => "subscribed", "Value" => true} ])```

As you might understand, it breaks, as you require here a numeric id. How do i do a simple lookup by email that would returns me the USEFUL id ?

**Comment by arnaudbreton** [comment]
Hi @bbnnt, it seems you managed to find a solution for your issue? I believe our community will benefit from seeing how you've fixed it on your side. 

From our side, I believe this is something we improved through the pull request #57. 

Let us know if you need further help here.
Best.
