### ISSUE TITLE
How can I specify a template for a transactional email ?

### ISSUE THREAD

**Issue by pinouchon** [mailjet/mailjet-gem#6]
The emails are correctly sent with mailjet. But I would like to be able to specify a template. This way, every sent emails look the same as the ones sent via the mailjet interface.

See http://stackoverflow.com/questions/17065913/how-to-specify-a-template-in-a-transational-email for more info

**Comment by SpainTrain** [comment]
Is this on the roadmap?  Mailjet looks great, but this is a critical feature for us.

**Comment by arnaudbreton** [comment]
Hi @SpainTrain, yes it is coming! Feel free to contact me at api@mailjet.com if you want to know more.
