### ISSUE TITLE
this gem feels bad.

### ISSUE THREAD

**Issue by bbnnt** [mailjet/mailjet-gem#60]
Just look at the id your api returns, depending on which language you use

`system("curl -s -X GET --user '#{ENV["MAILJET_API_KEY"]}:#{ENV["MAILJET_SECRET_KEY"]}' https://api.mailjet.com/v3/REST/contact/email@domain.tld")`

returns :
```
{ "Count" : 1, "Data" : [{ "CreatedAt" : "2016-01-28T09:07:10Z", "DeliveredCount" : 1, "Email" : "email@domain.tld", "ExclusionFromCampaignsUpdatedAt" : "", "ID" : 14541765, "IsExcludedFromCampaigns" : false, "IsOptInPending" : false, "IsSpamComplaining" : false, "LastActivityAt" : "2016-03-01T14:29:08Z", "LastUpdateAt" : "", "Name" : "", "UnsubscribedAt" : "", "UnsubscribedBy" : "" }], "Total" : 1 } => true
```

------------------------------------

`Mailjet::Contact.find("email@domain.tld")`

returns :
```
#<Mailjet::Contact:0x007f9698e5aae8 @attributes={"persisted"=>true, "created_at"=>Thu, 28 Jan 2016 09:07:10 +0000, "delivered_count"=>1, "email"=>"email@domain.tld", "exclusion_from_campaigns_updated_at"=>"", "id"=>"email@domain.tld", "is_excluded_from_campaigns"=>false, "is_opt_in_pending"=>false, "is_spam_complaining"=>false, "last_activity_at"=>Tue, 01 Mar 2016 14:29:08 +0000, "last_update_at"=>"", "name"=>"", "unsubscribed_at"=>"", "unsubscribed_by"=>""}> 
```

------------------------------------

You'll tell me, the curl method is not the same as the ruby method… no wait… the contact object differs from one language to another ? Wait no, there's multiple type of contact object ?

**Comment by arnaudbreton** [comment]
Hi @bbnnt, 

Sorry to read that your experience with our official gem was not as good as you were expecting.

From what I've understand here, there is no multiple definition of the contact object here, the confusion is mainly due to the fact that our gem is converting fields' names to snake case. Am I right?

Let us know how we can help you integrate successfully the library and Mailjet API in your application.
Best.

**Comment by bbnnt** [comment]
Look again maybe; you almost have the same result, but : with curl you get a numeric id, with ruby you get the email as the id

That's what i'd like to understand

**Comment by bbnnt** [comment]
So with such differences in ehats returned, and the camel case peoblem i haven't really experienced yet, shouldn't it be advised to stick with curl only ?

**Comment by arnaudbreton** [comment]
@bbnnt n'est-ce pas le même problème que remonté dans l'issue #59 que vous avez ouverte ? Le problème semble résolu depuis la release contenant la pull request #57

**Comment by bbnnt** [comment]
j'ai ça dans mon Gemfile : 
`gem 'mailjet', :git => 'https://github.com/mailjet/mailjet-gem.git'`

**Comment by arnaudbreton** [comment]
@bbnnt je vois que vous avez fermé l'issue. Avez-vous réussi à résoudre votre problème ? 

N'hésitez pas si nous pouvons vous aider.
Aussi, afin d'aider notre communauté à trouver des informations sur des issues récentes, nous apprécierions si vous pouviez mettre à jour le titre de l'issue vers quelque chose décrivant le problème que vous avez rencontré.

Merci de votre compréhension et bon vol avec l'API Mailjet !

**Comment by bbnnt** [comment]
alors avec `gem 'mailjet', :git => 'https://github.com/mailjet/mailjet-gem.git'`, et en appelant `Mailjet::Contact.find("email@domain.tld")`, je ne récupère pas l'id numérique (à savoir, #57 n'est à mon sens pas résolu, pour cette méthode spécifique on a du utiliser curb)

Mais bref, outre tout ce point spécifique assez déroutant au début, et le fait qu'on ait du le contourner, ça va finir par bien fonctionner
