### ISSUE TITLE
Emails not being sent when using templates

### ISSUE THREAD

**Issue by mustela** [mailjet/mailjet-gem#62]
When using templates emails are not being sent

```
    message = { from_email: 'my@email.com',
                subject: 'Confirmation instructions',
                'Mj-TemplateID' => 12345,
                'Mj-TemplateLanguage' => true,
                recipients: [{ email: 'hola@hola.com', name: 'My name' }],
                vars: { myvar: 'some value' }
              }
    Mailjet::Send.create(message)
```

But if I remove this line ` 'Mj-TemplateLanguage' => true,` the email is sent, but the variables are not being parsed.

**Comment by GuillaumeBadi** [comment]
Hey @mustela !

I am on it, sorry for the delay! In my opinion, it might be an error in the template itself, you can try to get the error back with this: http://dev.mailjet.com/guides/?ruby#templates-error-management

**Comment by mustela** [comment]
Hey @GuillaumeBadi its not working... would you mind to try it ?

```
  message = { from_email: 'help@mywebsite.io',
                subject: 'Confirmation instructions',
                'Mj-TemplateID' => 15205,
                'Mj-TemplateLanguage' => true,
                'Mj-TemplateErrorReporting' => 'emiliano@mywebsite.io',
                'Mj-TemplateErrorDeliver' => 'deliver',
                recipients: [{ email: 'ejankowski@mywebsite.com', name: 'Emiliano' }]
              }
    Mailjet::Send.create(message)
````

The email is just blocked and I am not getting any error report... I also created a ticket in the platform since there is no details at all, so I really don't know whats going on in here and I have no answer from you guys. 

<img width="1055" alt="screenshot 2016-03-11 16 56 32" src="https://cloud.githubusercontent.com/assets/325222/13707495/3e03822c-e7aa-11e5-8c9f-9e4d5de9b6af.png">

**Comment by GuillaumeBadi** [comment]
Can you give me your APIKEY and a messageID so we can investigate more on our side ?

**Comment by mustela** [comment]
ApiKey: 6a961d90f094999b30b5a817d047d2d2
https://app.mailjet.com/reports/emails/1pF6ioKLpP

**Comment by GuillaumeBadi** [comment]
We found the error returned by the API which is : 
```
status | error in template language: expression parsing error ## Unknown identifier: var:customer_first_name ## near ## {{var:customer_first_name ##
```

But in the logs it seems you did not set the Mj-TemplateErrorReporting

Can you send us your template at `api@mailjet.com` ?

**Comment by mustela** [comment]
Ive already fixed the template, but although I've set the `Mj-TemplateErrorReporting` prop, I never got an email.


```
 message = { from_email: 'help@mywebsite.io',
                subject: 'Confirmation instructions',
                'Mj-TemplateID' => 15205,
                'Mj-TemplateLanguage' => true,
                'Mj-TemplateErrorReporting' => 'emiliano@mywebsite.io',
                'Mj-TemplateErrorDeliver' => 'deliver',
                recipients: [{ email: 'ejankowski@mywebsite.com', name: 'Emiliano' }]
              }
    Mailjet::Send.create(message)

```

**Comment by GuillaumeBadi** [comment]
I think I finally got the solution! The old wrapper was filtering the properties before sending them, and you were using `Mj-TemplateErrorReporting` instead of `MJ-TemplateErrorReporting`. anyway, it does not filter anything now, please update the wrapper and everything should work!

**Comment by GuillaumeBadi** [comment]
I am closing the issue, please reopen if you encounter any problem :+1:

**Comment by mustela** [comment]
Cool, thanks, will check!

**Comment by lotfi10** [comment]
Hello, I use java as programming language in order to develop a spring boot microservice can communicate with MailJet API to send an email using my template configurated in my own  mailJet dashboard.

I tried to send the mail but I face an error :  error in template language

I used the same java code giver  by MailJet
I can give you all the details you need to check this error
Can you check @WeshGuillaume for me please
Thanks in advance
Lotfi

**Comment by dharani-gaddam** [comment]
I'm facing the same issue with just a basic hello world email template.
Can you please check @WeshGuillaume 
Thanks in advance
Dharani

**Comment by BigWenceslas** [comment]
```
$mj = new Client($_SERVER['MJ_APIKEY_PUBLIC'], $_SERVER['MJ_APIKEY_PRIVATE'], true, ['version' => 'v3.1']);
            $body = [
                'Messages' => [
                    [
                        'From' => [
                            'Email' => "no_reply@kbr-global.com",
                            'Name' => "Trust & Market"
                        ],
                        'To' => [
                            [
                                'Email' => $user_email,
                            ]
                        ],
                        'TemplateErrorReporting' => [
                            [
                                'Email' => "bessala93@gmail.com",
                                'Name' => "Web developper"
                            ]
                        ],
                        'TemplateID' => 5119890,
                        'TemplateLanguage' => true,
                        'Subject' => "Votre compte est supprimé !",
                        'Variables' => json_decode('{}', true)
                    ]
                ]
            ];
            $response = $mj->post(Resources::$Email, ['body' => $body]);
```
Same issue using PHP sdk. It is weird. I really dont understand this issue.
