### ISSUE TITLE
uninitialized constant Mailjet::Template

### ISSUE THREAD

**Issue by Maroo-b** [mailjet/mailjet-gem#70]
Hi, 

I was checking the API docs for creating transactional templates ([link](http://dev.mailjet.com/guides/?ruby#storing-a-template  ))

So when executing `Mailjet::Template.create(name: "First Template")` I got the following error:
`NameError: uninitialized constant Mailjet::Template`

From the gem code it seems this resource isn't yet implemented.

**Comment by GuillaumeBadi** [comment]
pull ;)

Thanks for reporting @Maroo-b, I appreciate 👍

**Comment by Maroo-b** [comment]
Nice work @GuillaumeBadi :) 
I added a PR https://github.com/mailjet/mailjet-gem/pull/71 to fix the url used for template detailcontent
