### ISSUE TITLE
Inline attachment typo ?

### ISSUE THREAD

**Issue by thibaultdalban** [mailjet/mailjet-gem#73]
I was digging into the code to understand something and I saw this line (https://github.com/mailjet/mailjet-gem/blob/master/lib/mailjet/mailer.rb#L34) :
```ruby
:inlineattachment => mail.attachments.select{ |a| !a.inline? }.try(:decoded)
``` 
Are you sure about the `!` before `a.inline?` ? It looks like a bad copy/paste of the previous line :
```ruby
:attachment => mail.attachments.select{ |a| !a.inline? }.try(:decoded)
```

**Comment by arnaudbreton** [comment]
Hi @thibaultdalban,

Really sorry for the delay to get back to you about that.

We've fixed some issues in our ActionMailer implementation in the [latest 1.4.9 release](https://github.com/mailjet/mailjet-gem/releases/tag/v1.4.9) and I believe this is part of the fixes we did.

Can you please confirm it works properly for you? 
I'm closing the issue now. Feel free to reopen this issue, or a new one if it's not the case on your side.

Thanks for your patience,
Best.

**Comment by thibaultdalban** [comment]
:+1:

**Comment by arnaudbreton** [comment]
Glad to read, thanks for the feedback.

hAPI coding with Mailjet API!
