### ISSUE TITLE
ActionMailer - From Name not being set

### ISSUE THREAD

**Issue by mscoutermarsh** [mailjet/mailjet-gem#74]
Hi,

Having issues when using action mailer with `:mailjet_api`. The `from_name` is not being set on emails we send.

I have this in my config settings.

```Ruby
 config.action_mailer.delivery_method = :mailjet_api
```

```Ruby
Mailjet.configure do |config|
  config.api_key = ..key..
  config.secret_key = ..key...
  config.default_from = 'My Name <example@example.com>'
end
```

But the name is not being set correctly in the from field for emails we send.

Emails are saying they are from "example@example.com", rather than "My Name"

Any ideas?

@GuillaumeBadi @eboisgon

**Comment by arnaudbreton** [comment]
Hey @mscoutermarsh, 

Apologies for the delay in our answer. I've just had a quick look at your issue and indeed, we do not use correctly the value set in `config.default_from` when passing it to our API, here https://github.com/mailjet/mailjet-gem/blob/77a76ef75bdceab0dfab5bb9c4e265ee53fe80e0/lib/mailjet/resource.rb#L89-L90

We should split the full from string into the two fields `FromEmail` and `FromName` as documented here http://dev.mailjet.com/guides/#send-api-json-properties

@GuillaumeBadi will have a look at it tomorrow and will implement this split so it'll be transparent for you. He'll keep you posted on our progress / the release fixing this issue.

Sorry about that.
Best,
Arnaud.

**Comment by mscoutermarsh** [comment]
Great, thanks! ❤️

**Comment by GuillaumeBadi** [comment]
Hey @mscoutermarsh ! ✈️ 

Freshly committed: https://github.com/mailjet/mailjet-gem/commit/c6e93ac4cb040804451f4f54c3a8ddd11f456908

can you test it on your side to check if everything is ok for you before the patch-release ? 😄 

Guillaume

**Comment by mscoutermarsh** [comment]
@GuillaumeBadi Hey :) Awesome! Will run some tests soon & update you. 😄

**Comment by mscoutermarsh** [comment]
@GuillaumeBadi Just tested and still seeing the same issue. I put a debugger into the mailjet gem and when we send mail via `mailjet_api` it never hits the method you modified (`create` in `Mailjet::Resource`).

I was thinking it would need to be added here: https://github.com/mailjet/mailjet-gem/blob/master/lib/mailjet/mailer.rb#L41-L43

Thanks 😄

**Comment by GuillaumeBadi** [comment]
Yep ! Sorry I added the code to use without ActionMailer, can you test it now ? 😅

**Comment by mscoutermarsh** [comment]
@GuillaumeBadi Which branch? I'm not seeing the new change.

**Comment by GuillaumeBadi** [comment]
My mistake sorry! now on `master`

**Comment by mscoutermarsh** [comment]
@GuillaumeBadi The `from_name` now works correctly. But the body of the email is blank.

I sent a multipart email. Both html & text are empty.

You guys have tests for this part of the gem?

**Comment by arnaudbreton** [comment]
Hi @mscoutermarsh,

Glad to hear the `from_name` is now working fine for you. About multipart, it's indeed not working properly and we're currently looking into that. Sorry about that.

Do you have a short code sample showing how you build the multipart message? We want to be sure we cover your use-case as well (since we're not Ruby/Rails experts here). 
Also, if you could share with us your environment (Rails and Ruby version, etc), again to be sure we make sure it'll work for you properly.

Thanks!

**Comment by mscoutermarsh** [comment]
No worries :). We're using SMTP right now. So I'm not in a rush on this.

We're on Rails: 4.2.7. Ruby: 2.2.2

For the mail, it's standard ActionMailer. If you follow this here: http://guides.rubyonrails.org/action_mailer_basics.html. The welcome email example they have. That's identical to how we do it. Separate text/html views. `SomeMailer.some_method(example).deliver_now`

Thanks

**Comment by arnaudbreton** [comment]
Hey @mscoutermarsh,

Thanks for the additional information and your patience. @GuillaumeBadi and I will make sure it works properly in this environment.

We've fixed most of the issues with our custom `ActionMailer` integration, and we plan to release it early this week. The code fixed is already present in [this branch](https://github.com/mailjet/mailjet-gem/tree/fix_actionmailer_api), feel free to test it.

Keep you posted,
Cheers.

**Comment by GuillaumeBadi** [comment]
Hey @mscoutermarsh !

Almost done on my side! Tests should be ready by tomorrow ! :)
https://github.com/mailjet/mailjet-gem/blob/fix_actionmailer_api/spec/mailjet/mailer_spec.rb

Guillaume

**Comment by mscoutermarsh** [comment]
awesome! Haven't had a chance to try yet, should be able to tomorrow. Thanks :)

**Comment by arnaudbreton** [comment]
Hi @mscoutermarsh,

The [1.4.9 release](https://github.com/mailjet/mailjet-gem/releases/tag/v1.4.9) contains all the fixes we validated on our side. Please let us know if it works for you.

Cheers

**Comment by mscoutermarsh** [comment]
woo @arnaudbreton @GuillaumeBadi thanks!

Just tried it & works perfectly. We'll put into production soon. Will let you know if we see any issues. Thanks :)

**Comment by arnaudbreton** [comment]
Awesome @mscoutermarsh, glad to hear! Thanks for your feedback and patience.
Please keep us posted about your production release.

**Comment by mscoutermarsh** [comment]
@arnaudbreton is in production. All good so far. Thanks :)

**Comment by arnaudbreton** [comment]
Glad to hear! Thanks for the feedback.
