### ISSUE TITLE
undefined method 'settings'

### ISSUE THREAD

**Issue by swaincreates** [mailjet/mailjet-gem#77]
I'm using mailjet_api with ActionMailer and on my staging server and I get:

```
Completed 500 Internal Service Error in 840ms (ActiveRecord: 5.7ms)
NoMethodError (undefined method 'settings' for #<Mailjet::APIMailer:0x00000006b62398>):
app/controllers/mailer_tests_controller.rb:3 in `app_submission`
```

I can create an email in the rails console using the Send API no problem, but getting the above problem when I use ActionMailer.

Any direction someone can point me?

**Comment by arnaudbreton** [comment]
Hi @swaincreates, 

Sorry to hear that and apologies for the delay in our answer.

In order to help you, I would need more information about how you declare things in your context.
I've just tested and everything works expected from my side.

Thanks!

**Comment by swaincreates** [comment]
Not sure what issue is. I switched from: 
`config.action_mailer.delivery_method = :mailjet_api`
to
`config.action_mailer.delivery_method = :mailjet`
and everything works great. Feel free to close!

**Comment by arnaudbreton** [comment]
Hey @swaincreates glad to hear!

Still, it seems the `:mailjet_api` delivery method (implementing our [transactional send api](https://dev.mailjet.com/guides/#send-transactional-email) in `ActionMailer`) goes wrong somewhere.

It would be very helpful if you could share your mailer code.

Thanks

**Comment by arnaudbreton** [comment]
Closing here, seems it looks similar to #79.
