### ISSUE TITLE
Email arrives with empty body

### ISSUE THREAD

**Issue by thehappycoder** [mailjet/mailjet-gem#79]
The email has a body:

```
TestMailer.test.body.raw_source
  Rendering test_mailer/test.html.erb
  Rendered test_mailer/test.html.erb (0.0ms)
TestMailer#test: processed outbound mail in 20.6ms
 => ":)\n"
```

But when I send it, it arrives without body.

Rails 5.0.0
mailjet 1.4.9

If you don't support this version of rails yet, please tell me when do you plan to.

**Comment by arnaudbreton** [comment]
Hi @thehappycoder,

Thanks for reaching out.
Apologies for the delay in our answer.

The mailer I'm using for my Rails tests works properly with Rails 5.0.0 and Mailjet 1.4.9. Could you please provide us with more details about how you initialise the wrapper on your side (`Mailjet.config` block), which sending method you use (`:mailjet` for SMTP or `:mailjet_api` for our [Transactional Send API](https://dev.mailjet.com/guides/?ruby#sending-a-basic-email)) and the way you declare things in your mailer?

Also, if you could provide us with IDs sent back by our system when sending (when using Send API), it could also help a lot.

Thanks!

**Comment by thehappycoder** [comment]
@arnaudbreton No worries

It seems to be working when I use :mailjet:
config.action_mailer.delivery_method = :mailjet

And it doesn't when I use :mailjet_api. It is worth mentioning that mailjet_api worked when I was using one of the beta versions of rails 5
I also get this stacktrace (which I didn't get/see before):
```
2.3.1 :001 > TestMailer.test.deliver!
  Rendering test_mailer/test.html.erb
  Rendered test_mailer/test.html.erb (2.6ms)
TestMailer#test: processed outbound mail in 484.8ms
NoMethodError: undefined method `settings' for #<Mailjet::APIMailer:0x007fb8c46cfd70>
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/mail-2.6.4/lib/mail/message.rb:255:in `deliver!'
	from /Users/anton/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
	from (irb):1
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/console.rb:65:in `start'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
	from /Users/anton/pwork/ivan/charity/bin/rails:9:in `<top (required)>'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/commands/rails.rb:6:in `call'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:191:in `block in serve'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:161:in `fork'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:161:in `serve'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
	from /Users/anton/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/anton/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/anton/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```
I see that I am not alone https://github.com/mailjet/mailjet-gem/issues/77

This is how I configure mailjet in initializers/mailjet.rb:
```
Mailjet.configure do |config|
  config.api_key = ENV['MAILJET_API_KEY']
  config.secret_key = ENV['MAILJET_SECRET_KEY']
  config.default_from = ENV['MAILJET_DEFAULT_FROM']
end
```

I think you have all information now?

**Comment by martinchenu** [comment]
@arnaudbreton I have the same issue here. I am using rails 4.

Since I changed 
 `config.action_mailer.delivery_method = :mailjet`
to
 `config.action_mailer.delivery_method = :mailjet_api`

MyBasicMailer.hello.deliver! is returning 
`MyBasicMailer#hello: processed outbound mail in 35.3ms
NoMethodError: undefined method 'settings' for #<Mailjet::APIMailer:0x007fe3645b6a90>` 

Does changing delivery_method is supposed to wrap Mail::Message objects into Mailjet::Send objects ?

I really need to have a response from this method in order to get the message id generated by the API.

Thank you for your help

**Comment by Zhivko-Mailjet** [comment]
Hi @martinchenu , @thehappycoder

@martinchenu After few test and reading the documentation of rails, it seems that adding a text.erb in the same folder as your html.erb could fix the error. You can find additional information and instructions in the session 2.1.3 of the official doc (here : http://guides.rubyonrails.org/action_mailer_basics.html#sending-emails ). Let me know if you still encounter problems after applying the changes.

@thehappycoder , @martinchenu about the second part of the issue (the settings), it looks like a call without the "!" doesn't give any problem. Could you please let me know whether "!" is mandatory for you and if so, why ?

**Comment by Zhivko-Mailjet** [comment]
Hi @martinchenu , @thehappycoder

I hope the suggestions worked for you guys and just wanted to check if that's the case.  Your feedback is always appreciated.
