### ISSUE TITLE
Send campaigns through the API

### ISSUE THREAD

**Issue by juliendemoutiez** [mailjet/mailjet-gem#80]
Hi,

I would like to send a newsletter using the API, but I'm not really sure how to proceed.

Basically, I already have my contact list so I would like to create a template on Mailjet, and then fill some field through the API (text and images). The best would be to reuse the same template every week and change the text fields and images.

Is this possible ? If yes, could you please tell me the steps I need to follow ?

Thank you very much,

J

**Comment by Zhivko-Mailjet** [comment]
Hi @martinchenu , @thehappycoder

@martinchenu After few test and reading the documentation of Rails, it seems that adding a text.erb file in the same folder as your html.erb could fix the error. You can find additional information and instructions in the session 2.1.3 of the official doc (here : http://guides.rubyonrails.org/action_mailer_basics.html#sending-emails ). Let me know if you still encounter problems after applying the changes.

@thehappycoder , @martinchenu about the second part of the issue (the settings), it looks like a call without the "!" doesn't give any problem. Could you please let me know whether "!" is mandatory for you and if so, why ?

**Comment by Zhivko-Mailjet** [comment]
Hi @juliendemoutiez ,

You can do the template in couple of different ways.

The first one is by using passport ( https://app.mailjet.com/signin ), create a template and put variables inside. See more information about Passport here:
https://www.mailjet.com/feature/passport/

The other option is to generate your template by passing the HTML and Text body directly. In the HTML body, you can insert your variables and define them each time you call our Send API. 
https://dev.mailjet.com/guides/#storing-a-template

The process will return an Template ID and you can use it in future. 
https://dev.mailjet.com/guides/#use-the-template-in-send-api

About the images, don't forget to attach them (like the seconde example of the section “sending with attached files” of the doc : https://dev.mailjet.com/guides/?ruby#sending-with-attached-files )

Hope this answers your questions.

**Comment by judemoutiez** [comment]
Thank you for your answer.

I would like to automate my newsletters, is it a good practice to adapt what is in the "Transactional templating" part of the API documentation ?

Thanks !

**Comment by Zhivko-Mailjet** [comment]
@judemoutiez 

Templating language is currently available for transactional emails only and it will not work with newsletters. 

For newsletters automation, you can check this part of the documentation, where we have some Ruby samples - https://dev.mailjet.com/guides/?ruby#send-marketing-campaigns

Hope it helps.

**Comment by judemoutiez** [comment]
Thanks for your answer.

I now manage to send campaigns but I'm struggling with responsiveness.

In your example you pass a very short Html body through the API. What is the best way to pass a longer html code (with styling) ? Can I store the template in a separate view ?

Thank you !

**Comment by Zhivko-Mailjet** [comment]
@judemoutiez 

We could offer you couple of solutions to fight the email unresponsiveness. 
1. Our responsive email editor. You can take advantage of the user friendly interface and drag and drop functionality. See more information here: https://www.mailjet.com/feature/passport/
2.  MJML - markup language for coding responsive email, developed by Mailjet. 
Explore MJML here: https://mjml.io/

Hope it helps.

**Comment by judemoutiez** [comment]
Thanks for your answer.

I must have misunderstood, I thought using Passport templates would not allow me to send newsletters via the API ? Is there a way I can create a Passport template and send it with dynamic variables through the API ?

The MJML markup language seems nice, but will I be able to use it through Rails API ?

Thanks again for your time !

**Comment by Zhivko-Mailjet** [comment]
@judemoutiez Sorry for the confusion created. 

You can indeed create template in Passport and send it through API, but keep in mind the following:

- In order to use customized variables, the message with template should be sent as transactional using our Send API (to specifc recipient, not to contacts list). Templating language is available for transactional messages only - https://dev.mailjet.com/guides/#use-the-template-in-send-api

- If you use our Newsletter API to send marketing campaings(to contacts list), you can not use templating language in there. You can use contact data - https://dev.mailjet.com/guides/?shell#personalisation-add-contact-properties

About MJML and Ruby, I believe you will find the article below pretty useful:
http://dev.edenspiekermann.com/2016/06/02/using-mjml-in-rails/

Hope I was able to clear your doubts.

**Comment by judemoutiez** [comment]
Hi, thanks for you answer.

I finally managed to send my newsletter with the API.
I have a last question, how can I add the unsubscribe link in the mail ?

Thanks !

**Comment by Zhivko-Mailjet** [comment]
Hi @juliendemoutiez 

I'm happy you were able to figure out the problem. Please refer to the article below in order to attach unsubscribe link to the newsletters:
https://www.mailjet.com/support/how-can-i-add-an-unsubscribe-link-to-my-newsletter,103.htm
