### ISSUE TITLE
Gem and docs different example

### ISSUE THREAD

**Issue by spyrbri** [mailjet/mailjet-gem#82]
[Here](https://github.com/mailjet/mailjet-gem#send-emails-with-actionmailer) you write
`headers['X-MJ-TemplateLanguage'] = '1'`
in the [docs](https://dev.mailjet.com/guides/#custom-headers) you write
`headers['X-MJ-TEMPLATELANGUAGE'] = 'True'`

Which one is correct?
P.S <del>both of them don't work for me.</del> Could you add an example where you send an e-mail with template language in it over SMTP with ActionMailer?

Update: 
I made it work with `headers['X-MJ-TemplateLanguage'] = '1'`.
I had `config.action_mailer.delivery_method = :mailjet` so none of them was working.

**Comment by Zhivko-Mailjet** [comment]
Hi @spyrbri,

Technically, both options should work.  To avoid any confusion, we corrected the README to match the official documentation.
headers['X-MJ-TemplateLanguage'] = 'true'
