### ISSUE TITLE
Socketerror - getaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by ckreutz** [mailjet/mailjet-gem#89]
For a few weeks now I keep on getting this error for sending emails. Most emails are sent, but here and there emails are not send with this error. Can this be related to the Gem in any way or some server issue on mailjet side? Thanks for any hints. 

The error happens on this point in the controller:

ExampleMailer.new_example(user, @example).deliver

**Comment by Zhivko-Mailjet** [comment]
@ckreutz 

Could you please share some more details:

- where your server is hosted ? If it is private local server, in which country it is located ?
- who is your DNS resolver/ ISP ?
- how often do you get this error ?
- do you get this error only when calling our SendAPI or you encounter it when calling other resources as well ?

**Comment by ckreutz** [comment]
@Zhivko-Mailjet thanks for the quick reply. We just discovered some DNS issues in our microservice architecture that might be the reason for it. Let me first investigate that further and close for now the issue. We try to play out some scenarios first. Thanks again for your  quick reply.

**Comment by ckreutz** [comment]
Okay we have looked further into the issue. We are running Rails apps on docker from a CoreOS server from Germany.  Public IP address all outbound traffic allowed. So far the issue seems to happen arbirtrary and we have the challenges to replicate the bug, but it keeps on coming on some of our app containers. 

Here is the error and it is always using ActionMailer on various Apps we have:

getaddrinfo: Name or service not known

/usr/local/lib/ruby/2.2.0/net/smtp.rb:541initialize

def tcp_socket(address, port)
      TCPSocket.open address, port
end

Next time it happens I will check if your API Url is available right in that container. But can you think of any other issue behind it? Thanks!

**Comment by Zhivko-Mailjet** [comment]
Hi @ckreutz 

Thanks for getting back. Issue doesn't seem to be related with the wrapper but with DNS resolution instead. Please open a [support ticket](https://www.mailjet.com/support), providing the previously requested information and we will dig into this on our end as well.

**Comment by ckreutz** [comment]
Just to follow-up on the issue. In the end it was a DNS issue on our bare metal server. Some containers were not picking up the correct DNS resolving. So it had noting to do with this gem.
