### ISSUE TITLE
Boolean property not update

### ISSUE THREAD

**Issue by tenzanoni** [mailjet/mailjet-gem#92]
I have a contact with active property (boolean, true as default). I used this command to set it to false but no luck even it run successfully with no error
```
Mailjet::Contactslist_managecontact.create(
      id: ENV['MAILJET_CONTACT_LIST_ID'],
      action: "addnoforce",
      email: email,
      properties: {
        active: false
      }
    )
```
If i set it to false manually, run the command above. It turn back to True.
Used this command to update another property type(string, int) and worked perfectly

**Comment by Zhivko-Mailjet** [comment]
@tenzanoni 
Could you please confirm whether you check the contact property value through the API or in the Web interface ?

**Comment by tenzanoni** [comment]
@Zhivko-Mailjet i checked on web UI

btw, this is what cmd return: #<Mailjet::Contactslist_managecontact:0x00000007b16f00 @attributes={"persisted"=>false, "action"=>"addnoforce", "email"=>"xxxxx@gmail.com", "properties"=>{"first_name"=>"xxxx", "name"=>"xxxx", "active"=>false}, "contact_id"=>xxxxxxx, "name"=>""}, @persisted=true>

go check in web UI, active value is still true

**Comment by Zhivko-Mailjet** [comment]
Hi @tenzanoni 
Thanks for the clarification. The boolean properties are stored correctly on our API, but are displayed always as True in the WebUI. We are aware of this issue and our Front End team is working on resolving it.

In the meantime, you should be able to use the contact properties normally through the API, as the real values are kept. 

Thanks for reporting the problem and sorry for any inconvenience.

**Comment by tenzanoni** [comment]
@Zhivko-Mailjet  cool, i will close this then
