### ISSUE TITLE
Resource instances don't hit API?

### ISSUE THREAD

**Issue by excid3** [mailjet/mailjet-gem#96]
Was doing some debugging today and noticed that resource instance methods like `update_attributes` don't hit the API. Since instance methods don't call the `change_resource_path` like the class methods do, they don't get the correct endpoint, version, and so on.

```ruby
# class method, correctly hits API
c = Mailjet::Contactdata.find("name@address.com") 

# instance method, immediately returns true without hitting the API
c.update_attributes("data"=>[{"Name"=>"plan", "Value"=>"monthly"}])
```

Should these methods be updated in `Resource` to call that? For example, modifying the method like this works:

```ruby
    def update_attributes(attribute_hash = {}, options = {})
      self.attributes = attribute_hash
      opts = self.class.change_resource_path(options) # this was added to get the default config
      save(opts)
    end
```

**Comment by Zhivko-Mailjet** [comment]
Hi @excid3 

Thanks for spotting and reporting the problem. We will investigate further on our end. 

In the meantime, we will be more than happy to review your contribution

**Comment by Lorel** [comment]
Hi @excid3

Indeed, nice catch!
2fc4bccc6f016adb3b30e0984dae59b35497bdd9 should fix that

**Comment by arnaudbreton** [comment]
Hi @excid3, I've just published v1.5.1 which contains the fix @Lorel mentioned just above. It's available on Rubygems.

Hope it works for you, please let us know.
Anyway, many thanks for reporting it and for having chosen Mailjet to power your emails.

**Comment by excid3** [comment]
Fantastic, thanks guys! Will update to that and let you know if I run into any issues.

**Comment by arnaudbreton** [comment]
Awesome, thanks @excid3 for your feedback and time. Looking forward to hear back!
